-- ==========================================================
-- COMPREHENSIVE DATABASE FIX SCRIPT
-- ==========================================================
-- This script fixes common schema mismatches by adding missing
-- columns, tables, and functions required for Courses & Enrollment.
-- 
-- HOW TO USE:
-- 1. Go to your Supabase Dashboard
-- 2. Click on "SQL Editor" in the left sidebar
-- 3. Click "New Query"
-- 4. Paste this entire script and click "Run"
-- ==========================================================

-- 1. FIX UPLOADS TABLE
DO $$ 
BEGIN 
    -- Add category column
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'uploads' AND column_name = 'category') THEN 
        ALTER TABLE uploads ADD COLUMN category text DEFAULT 'source_document'; 
    END IF;

    -- Add level column
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'uploads' AND column_name = 'level') THEN 
        ALTER TABLE uploads ADD COLUMN level text DEFAULT 'All'; 
    END IF;

    -- Add file_type column
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'uploads' AND column_name = 'file_type') THEN 
        ALTER TABLE uploads ADD COLUMN file_type text; 
    END IF;

    -- Add file_url column
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'uploads' AND column_name = 'file_url') THEN 
        ALTER TABLE uploads ADD COLUMN file_url text; 
    END IF;
END $$;


-- 2. CREATE ENROLLMENT KEYS TABLE
CREATE TABLE IF NOT EXISTS enrollment_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_code text UNIQUE NOT NULL,
  course_id bigint REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
  created_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  creator_role text,
  max_uses integer DEFAULT NULL,
  current_uses integer DEFAULT 0,
  max_students integer DEFAULT NULL,
  valid_from timestamptz DEFAULT now(),
  valid_until timestamptz DEFAULT NULL,
  is_active boolean DEFAULT true,
  description text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Enable RLS for enrollment_keys
ALTER TABLE enrollment_keys ENABLE ROW LEVEL SECURITY;

-- 3. UPDATE ENROLLMENTS TABLE
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'enrollments' AND column_name = 'enrollment_key_id') THEN
        ALTER TABLE enrollments ADD COLUMN enrollment_key_id bigint REFERENCES enrollment_keys(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'enrollments' AND column_name = 'enrollment_method') THEN
        ALTER TABLE enrollments ADD COLUMN enrollment_method text DEFAULT 'manual';
    END IF;
END $$;


-- 4. HELPER FUNCTIONS FOR ENROLLMENT
CREATE OR REPLACE FUNCTION validate_enrollment_key(p_key_code text)
RETURNS TABLE (
  valid boolean,
  error_message text,
  key_id bigint,
  course_id bigint,
  course_name text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_key enrollment_keys%ROWTYPE;
  v_course_name text;
BEGIN
  SELECT * INTO v_key FROM enrollment_keys WHERE key_code = p_key_code;
  IF v_key.id IS NULL THEN
    RETURN QUERY SELECT false, 'Invalid enrollment key'::text, NULL::bigint, NULL::bigint, NULL::text;
    RETURN;
  END IF;
  IF v_key.is_active = false THEN
    RETURN QUERY SELECT false, 'This enrollment key has been deactivated'::text, NULL::bigint, NULL::bigint, NULL::text;
    RETURN;
  END IF;
  IF v_key.valid_until IS NOT NULL AND now() > v_key.valid_until THEN
    RETURN QUERY SELECT false, 'This enrollment key has expired'::text, NULL::bigint, NULL::bigint, NULL::text;
    RETURN;
  END IF;
  IF v_key.max_uses IS NOT NULL AND v_key.current_uses >= v_key.max_uses THEN
    RETURN QUERY SELECT false, 'This enrollment key has reached its usage limit'::text, NULL::bigint, NULL::bigint, NULL::text;
    RETURN;
  END IF;
  SELECT name INTO v_course_name FROM courses WHERE id = v_key.course_id;
  RETURN QUERY SELECT true, ''::text, v_key.id, v_key.course_id, v_course_name;
END;
$$;

CREATE OR REPLACE FUNCTION use_enrollment_key(p_key_code text, p_user_id uuid)
RETURNS TABLE (
  success boolean,
  error_message text,
  enrollment_id bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_validation RECORD;
  v_existing_enrollment bigint;
  v_new_enrollment_id bigint;
BEGIN
  SELECT * INTO v_validation FROM validate_enrollment_key(p_key_code);
  IF NOT v_validation.valid THEN
    RETURN QUERY SELECT false, v_validation.error_message, NULL::bigint;
    RETURN;
  END IF;
  SELECT id INTO v_existing_enrollment FROM enrollments WHERE user_id = p_user_id AND course_id = v_validation.course_id;
  IF v_existing_enrollment IS NOT NULL THEN
    RETURN QUERY SELECT false, 'You are already enrolled in this course'::text, v_existing_enrollment;
    RETURN;
  END IF;
  INSERT INTO enrollments (user_id, course_id, enrollment_key_id, enrollment_method)
  VALUES (p_user_id, v_validation.course_id, v_validation.key_id, 'key')
  RETURNING id INTO v_new_enrollment_id;
  UPDATE enrollment_keys SET current_uses = current_uses + 1, updated_at = now() WHERE id = v_validation.key_id;
  RETURN QUERY SELECT true, 'Successfully enrolled'::text, v_new_enrollment_id;
END;
$$;


-- 5. FIX QUESTIONS TABLE
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'questions' AND column_name = 'upload_id') THEN
        ALTER TABLE questions ADD COLUMN upload_id bigint REFERENCES uploads(id) ON DELETE CASCADE;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'questions' AND column_name = 'image') THEN
        ALTER TABLE questions ADD COLUMN image text;
    END IF;
END $$;


-- 6. POLICIES (GIVING MINIMAL ACCESS)
DO $$ 
BEGIN
    DROP POLICY IF EXISTS "Anyone can validate enrollment keys" ON enrollment_keys;
    CREATE POLICY "Anyone can validate enrollment keys" ON enrollment_keys FOR SELECT USING (is_active = true);
    
    DROP POLICY IF EXISTS "Admins and tutors can create enrollment keys" ON enrollment_keys;
    CREATE POLICY "Admins and tutors can create enrollment keys" ON enrollment_keys FOR INSERT TO authenticated 
    WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'admin' OR role = 'tutor')));
END $$;


-- ==========================================================
-- FINISHED! Please run this in your Supabase SQL Editor.
-- ==========================================================
