-- ==========================================================
-- EMERGENCY FIX: MISSING TABLES & PERMISSIONS
-- ==========================================================

-- 1. Create invitation_links table
CREATE TABLE IF NOT EXISTS invitation_links (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invite_code text UNIQUE NOT NULL,
  invite_url text NOT NULL,
  created_by uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  creator_role text NOT NULL,
  course_id bigint REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
  auto_enroll boolean DEFAULT true,
  max_uses integer DEFAULT NULL,
  current_uses integer DEFAULT 0,
  valid_until timestamptz DEFAULT NULL,
  allowed_emails text[] DEFAULT NULL,
  required_email_domain text,
  is_active boolean DEFAULT true,
  description text,
  custom_message text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 2. Create invitation_uses table
CREATE TABLE IF NOT EXISTS invitation_uses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invitation_id bigint REFERENCES invitation_links(id) ON DELETE CASCADE NOT NULL,
  user_id uuid REFERENCES profiles(id) ON DELETE CASCADE,
  email text NOT NULL,
  ip_address text,
  user_agent text,
  registration_completed boolean DEFAULT false,
  enrolled_in_course boolean DEFAULT false,
  created_at timestamptz DEFAULT now()
);

-- 3. Enable RLS
ALTER TABLE invitation_links ENABLE ROW LEVEL SECURITY;
ALTER TABLE invitation_uses ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_groups ENABLE ROW LEVEL SECURITY;
ALTER TABLE group_members ENABLE ROW LEVEL SECURITY;

-- 4. RLS Policies for Invitation Links
DROP POLICY IF EXISTS "Public can view active invitations" ON invitation_links;
CREATE POLICY "Public can view active invitations" ON invitation_links FOR SELECT USING (is_active = true);

DROP POLICY IF EXISTS "Users can view own invitations" ON invitation_links;
CREATE POLICY "Users can view own invitations" ON invitation_links FOR SELECT TO authenticated
USING (created_by = auth.uid() OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

DROP POLICY IF EXISTS "Admins and tutors can create invitations" ON invitation_links;
CREATE POLICY "Admins and tutors can create invitations" ON invitation_links FOR INSERT TO authenticated
WITH CHECK (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND (role = 'admin' OR (role = 'tutor' AND tutor_approved = true))));

-- 5. RLS Policies for Student Groups
DROP POLICY IF EXISTS "Tutors can manage own groups" ON student_groups;
CREATE POLICY "Tutors can manage own groups" ON student_groups FOR ALL TO authenticated
USING (created_by = auth.uid() OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- 6. Helper Function: exec_sql (Very useful for the AI to fix things later)
CREATE OR REPLACE FUNCTION exec_sql(sql_query text)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  EXECUTE sql_query;
  RETURN jsonb_build_object('status', 'success');
EXCEPTION WHEN OTHERS THEN
  RETURN jsonb_build_object('status', 'error', 'message', SQLERRM);
END;
$$;
