
const { createClient } = require('@supabase/supabase-js');
require('dotenv').config();

async function fixInternalSettings() {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_SERVICE_ROLE_KEY);
    
    console.log('🔧 Fixing internal_settings table and api_config column...');
    
    const sql = `
    -- 1. Create internal_settings table if it doesn't exist
    CREATE TABLE IF NOT EXISTS public.internal_settings (
        id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
        app_name text DEFAULT 'Educational AI',
        api_config jsonb DEFAULT '{}'::jsonb,
        created_at timestamptz DEFAULT now(),
        updated_at timestamptz DEFAULT now()
    );

    -- 2. Ensure api_config column exists
    DO $$ 
    BEGIN 
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'internal_settings' AND column_name = 'api_config') THEN 
            ALTER TABLE public.internal_settings ADD COLUMN api_config jsonb DEFAULT '{}'::jsonb; 
        END IF;
    END $$;

    -- 3. Insert initial row if empty
    INSERT INTO public.internal_settings (id, app_name, api_config)
    SELECT 1, 'Educational AI', '{}'::jsonb
    WHERE NOT EXISTS (SELECT 1 FROM public.internal_settings WHERE id = 1);

    -- 4. Enable RLS and add basic policies
    ALTER TABLE public.internal_settings ENABLE ROW LEVEL SECURITY;
    DROP POLICY IF EXISTS "Public read settings" ON public.internal_settings;
    CREATE POLICY "Public read settings" ON public.internal_settings FOR SELECT USING (true);
    
    DROP POLICY IF EXISTS "Admins manage settings" ON public.internal_settings;
    CREATE POLICY "Admins manage settings" ON public.internal_settings FOR ALL TO authenticated 
    USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));
    `;

    const { data, error } = await supabase.rpc('exec_sql', { sql_query: sql });

    if (error) {
        console.error('❌ Error executing fix:', error.message);
    } else {
        console.log('✅ internal_settings fix applied successfully!');
        console.log('Result:', data);
    }
}

fixInternalSettings().catch(console.error);
