services:
  - type: web
    name: aitutor-backend
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: GMAIL_USER
        value: ssky57771@gmail.com
      - key: GMAIL_APP_PASS
        value: hxlhrbzchvlugvud
      - key: EMAIL_USER
        value: ssky57771@gmail.com
      - key: EMAIL_PASS
        value: hxlhrbzchvlugvud
      - key: EMAIL_FROM
        value: ssky57771@gmail.com
      - key: APP_NAME
        value: AI Tutor Platform
