-- Create the student_states table for the Agent Tutor
create table if not exists student_states (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null unique,
  goal text,
  baseline jsonb,
  mastery jsonb default '{}'::jsonb,
  timing jsonb default '{}'::jsonb,
  error_patterns jsonb default '{}'::jsonb,
  preferences jsonb default '{}'::jsonb,
  session_log jsonb default '[]'::jsonb,
  current_state text,
  session_focus text,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table student_states enable row level security;

-- Drop existing policies to avoid conflicts
drop policy if exists "Users can view their own state" on student_states;
drop policy if exists "Users can update their own state" on student_states;
drop policy if exists "Users can insert their own state" on student_states;

-- Policies
create policy "Users can view their own state"
  on student_states for select
  using ( auth.uid() = user_id );

create policy "Users can update their own state"
  on student_states for update
  using ( auth.uid() = user_id );

create policy "Users can insert their own state"
  on student_states for insert
  with check ( auth.uid() = user_id );
