
-- ULTIMATE RECURSION-FREE RLS FIX
-- Uses JWT claims to avoid querying the profiles table during policy checks.

-- 1. Ensure internal_settings has required columns
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.tables WHERE table_name = 'internal_settings') THEN
        CREATE TABLE public.internal_settings (
            id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            app_name text DEFAULT 'Educational AI',
            api_config jsonb DEFAULT '{}'::jsonb,
            created_at timestamptz DEFAULT now(),
            updated_at timestamptz DEFAULT now()
        );
    ELSE
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'internal_settings' AND column_name = 'api_config') THEN 
            ALTER TABLE public.internal_settings ADD COLUMN api_config jsonb DEFAULT '{}'::jsonb; 
        END IF;
        IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'internal_settings' AND column_name = 'app_name') THEN 
            ALTER TABLE public.internal_settings ADD COLUMN app_name text DEFAULT 'Educational AI'; 
        END IF;
    END IF;
END $$;

-- 2. Drop the recursive helper functions
DROP FUNCTION IF EXISTS public.check_admin_status();
DROP FUNCTION IF EXISTS public.is_admin();
DROP FUNCTION IF EXISTS public.is_tutor();

-- 3. Apply NEW RLS for PROFILES (Read is public to authenticated, write is strict)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

DO $$ 
DECLARE 
  pol RECORD;
BEGIN 
  FOR pol IN (SELECT policyname FROM pg_policies WHERE tablename = 'profiles' AND schemaname = 'public') 
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON profiles', pol.policyname);
  END LOOP;
END $$;

-- Policy: Authenticated users can read ALl profiles (to see names/roles)
-- NO RECURSION: true doesn't query anything
CREATE POLICY "profiles_read_all" ON public.profiles FOR SELECT TO authenticated USING (true);

-- Policy: Users update their own
CREATE POLICY "profiles_update_self" ON public.profiles FOR UPDATE TO authenticated USING (id = auth.uid());

-- Policy: Admins can do everything (using JWT claim if possible, or fallback function)
CREATE POLICY "profiles_admin_all" ON public.profiles FOR ALL TO authenticated 
USING (COALESCE(auth.jwt() ->> 'role', '') = 'admin');

-- 4. Apply NEW RLS for INTERNAL_SETTINGS
ALTER TABLE public.internal_settings ENABLE ROW LEVEL SECURITY;

DO $$ 
DECLARE 
  pol RECORD;
BEGIN 
  FOR pol IN (SELECT policyname FROM pg_policies WHERE tablename = 'internal_settings' AND schemaname = 'public') 
  LOOP
    EXECUTE format('DROP POLICY IF EXISTS %I ON internal_settings', pol.policyname);
  END LOOP;
END $$;

CREATE POLICY "settings_read_all" ON public.internal_settings FOR SELECT TO authenticated USING (true);
CREATE POLICY "settings_admin_all" ON public.internal_settings FOR ALL TO authenticated 
USING (COALESCE(auth.jwt() ->> 'role', '') = 'admin');

-- 5. Restore metadata for existing users to ensure JWT role is present
UPDATE auth.users u
SET raw_user_meta_data = 
  COALESCE(raw_user_meta_data, '{}'::jsonb) || 
  jsonb_build_object('role', p.role, 'name', p.name)
FROM public.profiles p
WHERE u.id = p.id;
