/* 
# Create Enrollments Table
1. New Tables
   - `enrollments`
     - `id` (bigint, primary key)
     - `user_id` (uuid, fk to profiles)
     - `course_id` (bigint, fk to courses)
     - `enrolled_at` (timestamp)
2. Security
   - Enable RLS
   - Policies for students to manage their own enrollments
*/

CREATE TABLE IF NOT EXISTS enrollments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  course_id bigint REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
  enrolled_at timestamptz DEFAULT now(),
  UNIQUE(user_id, course_id)
);

ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;

-- Students can view their own enrollments
CREATE POLICY "Users can view own enrollments" 
  ON enrollments FOR SELECT 
  TO authenticated 
  USING (auth.uid() = user_id);

-- Students can enroll themselves
CREATE POLICY "Users can enroll themselves" 
  ON enrollments FOR INSERT 
  TO authenticated 
  WITH CHECK (auth.uid() = user_id);

-- Admins can view all (Optional, good for management)
CREATE POLICY "Admins can view all enrollments" 
  ON enrollments FOR SELECT 
  TO authenticated 
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));