/*
# Add Uploads Table

1. New Tables
   - `uploads`
     - `id` (bigint, primary key)
     - `course_id` (bigint, fk to courses)
     - `file_name` (text)
     - `status` (text)
     - `questions_count` (int)
     - `created_at` (timestamp)

2. Security
   - Enable RLS
   - Policies for Admins
*/

CREATE TABLE IF NOT EXISTS uploads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id bigint REFERENCES courses(id) ON DELETE CASCADE,
  file_name text,
  status text,
  questions_count integer DEFAULT 0,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE uploads ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Uploads are viewable by authenticated users" 
ON uploads FOR SELECT TO authenticated USING (true);

CREATE POLICY "Uploads are insertable by admins" 
ON uploads FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

CREATE POLICY "Uploads are deletable by admins" 
ON uploads FOR DELETE TO authenticated USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);