/* 
# Initial Schema Setup

1. New Tables
   - `profiles`
     - `id` (uuid, primary key, references auth.users)
     - `email` (text)
     - `name` (text)
     - `role` (text) - 'admin' or 'student'
     - `created_at` (timestamp)
   - `courses`
     - `id` (bigint, primary key)
     - `name` (text)
     - `description` (text)
     - `levels` (text array)
     - `questions_count` (integer) - cached count
     - `created_at` (timestamp)
   - `questions`
     - `id` (bigint, primary key)
     - `course_id` (bigint, foreign key)
     - `level` (text)
     - `type` (text)
     - `question` (text)
     - `options` (text array)
     - `correct_answer` (text)
     - `explanation` (text)
     - `image` (text)
     - `created_at` (timestamp)

2. Security
   - Enable RLS on all tables
   - Add policies for read/write access based on roles
*/

-- Create profiles table
CREATE TABLE IF NOT EXISTS profiles (
  id uuid REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  email text,
  name text,
  role text DEFAULT 'student',
  created_at timestamptz DEFAULT now()
);

-- Create courses table
CREATE TABLE IF NOT EXISTS courses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  description text,
  levels text[] DEFAULT '{Easy,Medium,Hard}',
  questions_count integer DEFAULT 0,
  start_date timestamptz,
  created_at timestamptz DEFAULT now()
);

-- Create questions table
CREATE TABLE IF NOT EXISTS questions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_id bigint REFERENCES courses(id) ON DELETE CASCADE,
  level text,
  type text,
  question text NOT NULL,
  options text[],
  correct_answer text,
  explanation text,
  image text,
  created_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE questions ENABLE ROW LEVEL SECURITY;

-- Profiles Policies
CREATE POLICY "Public profiles are viewable by everyone" 
ON profiles FOR SELECT USING (true);

CREATE POLICY "Users can insert their own profile" 
ON profiles FOR INSERT WITH CHECK (auth.uid() = id);

CREATE POLICY "Users can update own profile" 
ON profiles FOR UPDATE USING (auth.uid() = id);

-- Courses Policies
CREATE POLICY "Courses are viewable by authenticated users" 
ON courses FOR SELECT TO authenticated USING (true);

CREATE POLICY "Courses are insertable by admins" 
ON courses FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

CREATE POLICY "Courses are updatable by admins" 
ON courses FOR UPDATE TO authenticated USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

CREATE POLICY "Courses are deletable by admins" 
ON courses FOR DELETE TO authenticated USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Questions Policies
CREATE POLICY "Questions are viewable by authenticated users" 
ON questions FOR SELECT TO authenticated USING (true);

CREATE POLICY "Questions are insertable by admins" 
ON questions FOR INSERT TO authenticated WITH CHECK (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

CREATE POLICY "Questions are updatable by admins" 
ON questions FOR UPDATE TO authenticated USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

CREATE POLICY "Questions are deletable by admins" 
ON questions FOR DELETE TO authenticated USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);