/* 
# Contact & Leaderboard Features

1. New Tables
   - `contact_messages`: Stores public contact form submissions.
     - `full_name`, `mobile`, `email`, `message`
     - RLS: Public INSERT allowed.

2. New Views
   - `leaderboard`: Aggregates student progress to calculate rankings.
     - Calculates `total_score` (sum of quiz scores) and `courses_completed`.
*/

-- 1. Contact Messages Table
CREATE TABLE IF NOT EXISTS contact_messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text NOT NULL,
  mobile text,
  email text NOT NULL,
  message text NOT NULL,
  created_at timestamptz DEFAULT now()
);

ALTER TABLE contact_messages ENABLE ROW LEVEL SECURITY;

-- Allow ANYONE (including unauthenticated) to insert messages
CREATE POLICY "Public can send messages" ON contact_messages 
  FOR INSERT WITH CHECK (true);

-- Only Admins can view messages
CREATE POLICY "Admins view messages" ON contact_messages 
  FOR SELECT TO authenticated 
  USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));


-- 2. Leaderboard View
-- Aggregates scores from student_progress table
CREATE OR REPLACE VIEW leaderboard AS
SELECT 
  p.id as user_id,
  p.name,
  COALESCE(SUM(sp.score), 0) as total_points,
  COUNT(sp.id) as levels_completed,
  MAX(sp.created_at) as last_active
FROM profiles p
LEFT JOIN student_progress sp ON p.id = sp.user_id
WHERE p.role = 'student'
GROUP BY p.id, p.name
ORDER BY total_points DESC;

-- Grant access to view
GRANT SELECT ON leaderboard TO authenticated;