/*
# Fix Enrollment Permissions
1. Grants explicit permissions to `authenticated` role on `enrollments` table.
2. Ensures the table exists and RLS is enabled.
3. Ensures policies are correctly applied.
*/

-- Ensure table exists (idempotent)
CREATE TABLE IF NOT EXISTS enrollments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  course_id bigint REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
  enrolled_at timestamptz DEFAULT now(),
  UNIQUE(user_id, course_id)
);

-- Enable RLS
ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;

-- Grant permissions (CRITICAL FIX)
GRANT ALL ON enrollments TO postgres, service_role;
GRANT SELECT, INSERT, DELETE ON enrollments TO authenticated;

-- Ensure policies exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'enrollments' AND policyname = 'Users can view own enrollments'
    ) THEN
        CREATE POLICY "Users can view own enrollments" ON enrollments FOR SELECT TO authenticated USING (auth.uid() = user_id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE tablename = 'enrollments' AND policyname = 'Users can enroll themselves'
    ) THEN
        CREATE POLICY "Users can enroll themselves" ON enrollments FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
    END IF;
END
$$;