/*
# Fix Enrollment Robustness
1. Reset RLS policies for `enrollments` to ensure no conflicts.
2. Grant explicit permissions to authenticated users.
3. Ensure `enrollments` table has correct foreign keys and constraints.
*/

-- 1. Ensure Table Structure (Idempotent)
CREATE TABLE IF NOT EXISTS enrollments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  course_id bigint REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
  enrolled_at timestamptz DEFAULT now(),
  UNIQUE(user_id, course_id)
);

-- 2. Reset Policies (Drop and Recreate)
DROP POLICY IF EXISTS "Users can view own enrollments" ON enrollments;
DROP POLICY IF EXISTS "Users can enroll themselves" ON enrollments;
DROP POLICY IF EXISTS "Admins can view all enrollments" ON enrollments;

ALTER TABLE enrollments ENABLE ROW LEVEL SECURITY;

-- Policy: View Own
CREATE POLICY "Users can view own enrollments" 
ON enrollments FOR SELECT 
TO authenticated 
USING (auth.uid() = user_id);

-- Policy: Insert Own (Enroll)
CREATE POLICY "Users can enroll themselves" 
ON enrollments FOR INSERT 
TO authenticated 
WITH CHECK (auth.uid() = user_id);

-- Policy: Delete Own (Unenroll - optional but good for testing)
CREATE POLICY "Users can unenroll themselves" 
ON enrollments FOR DELETE 
TO authenticated 
USING (auth.uid() = user_id);

-- 3. Grant Permissions to Roles
GRANT ALL ON enrollments TO postgres, service_role;
GRANT SELECT, INSERT, DELETE ON enrollments TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE enrollments_id_seq TO authenticated;