/* 
# Create Enrollment Keys System
1. New Table: enrollment_keys
2. Update enrollments table to track enrollment method
3. Add RLS policies
4. Create helper functions
*/

-- Create enrollment_keys table
CREATE TABLE IF NOT EXISTS enrollment_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Key Information
  key_code text UNIQUE NOT NULL,
  course_id bigint REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
  
  -- Created By
  created_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  creator_role text,
  
  -- Restrictions
  max_uses integer DEFAULT NULL,
  current_uses integer DEFAULT 0,
  max_students integer DEFAULT NULL,
  valid_from timestamptz DEFAULT now(),
  valid_until timestamptz DEFAULT NULL,
  
  -- Status
  is_active boolean DEFAULT true,
  
  -- Metadata
  description text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Indexes for enrollment_keys
CREATE INDEX IF NOT EXISTS idx_enrollment_keys_course ON enrollment_keys(course_id);
CREATE INDEX IF NOT EXISTS idx_enrollment_keys_code ON enrollment_keys(key_code);
CREATE INDEX IF NOT EXISTS idx_enrollment_keys_active ON enrollment_keys(is_active) WHERE is_active = true;
CREATE INDEX IF NOT EXISTS idx_enrollment_keys_creator ON enrollment_keys(created_by);

-- Enable RLS
ALTER TABLE enrollment_keys ENABLE ROW LEVEL SECURITY;

-- RLS Policies for enrollment_keys

-- Anyone can validate keys (needed for enrollment)
CREATE POLICY "Anyone can validate enrollment keys"
ON enrollment_keys FOR SELECT
USING (is_active = true);

-- Creators can view their own keys
CREATE POLICY "Users can view own enrollment keys"
ON enrollment_keys FOR SELECT TO authenticated
USING (
  created_by = auth.uid() OR
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Admins and approved tutors can create keys
CREATE POLICY "Admins and tutors can create enrollment keys"
ON enrollment_keys FOR INSERT TO authenticated
WITH CHECK (
  EXISTS (
    SELECT 1 FROM profiles 
    WHERE id = auth.uid() 
    AND (
      role = 'admin' OR 
      (role = 'tutor' AND tutor_approved = true)
    )
  )
);

-- Creators can update their keys
CREATE POLICY "Creators can update enrollment keys"
ON enrollment_keys FOR UPDATE TO authenticated
USING (
  created_by = auth.uid() OR 
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Creators can delete their keys
CREATE POLICY "Creators can delete enrollment keys"
ON enrollment_keys FOR DELETE TO authenticated
USING (
  created_by = auth.uid() OR 
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Update enrollments table to track enrollment method
DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'enrollments' AND column_name = 'enrollment_key_id') THEN
        ALTER TABLE enrollments ADD COLUMN enrollment_key_id bigint REFERENCES enrollment_keys(id) ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'enrollments' AND column_name = 'enrollment_method') THEN
        ALTER TABLE enrollments ADD COLUMN enrollment_method text DEFAULT 'manual';
    END IF;
END $$;

-- Create index for enrollment key lookups
CREATE INDEX IF NOT EXISTS idx_enrollments_key ON enrollments(enrollment_key_id);

-- Function to validate enrollment key
CREATE OR REPLACE FUNCTION validate_enrollment_key(p_key_code text)
RETURNS TABLE (
  valid boolean,
  error_message text,
  key_id bigint,
  course_id bigint,
  course_name text
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_key enrollment_keys%ROWTYPE;
  v_course_name text;
BEGIN
  -- Get the key
  SELECT * INTO v_key FROM enrollment_keys WHERE key_code = p_key_code;
  
  -- Check if key exists
  IF v_key.id IS NULL THEN
    RETURN QUERY SELECT false, 'Invalid enrollment key'::text, NULL::bigint, NULL::bigint, NULL::text;
    RETURN;
  END IF;
  
  -- Check if key is active
  IF v_key.is_active = false THEN
    RETURN QUERY SELECT false, 'This enrollment key has been deactivated'::text, NULL::bigint, NULL::bigint, NULL::text;
    RETURN;
  END IF;
  
  -- Check valid_from date
  IF v_key.valid_from IS NOT NULL AND now() < v_key.valid_from THEN
    RETURN QUERY SELECT false, 'This enrollment key is not yet valid'::text, NULL::bigint, NULL::bigint, NULL::text;
    RETURN;
  END IF;
  
  -- Check valid_until date
  IF v_key.valid_until IS NOT NULL AND now() > v_key.valid_until THEN
    RETURN QUERY SELECT false, 'This enrollment key has expired'::text, NULL::bigint, NULL::bigint, NULL::text;
    RETURN;
  END IF;
  
  -- Check max_uses
  IF v_key.max_uses IS NOT NULL AND v_key.current_uses >= v_key.max_uses THEN
    RETURN QUERY SELECT false, 'This enrollment key has reached its usage limit'::text, NULL::bigint, NULL::bigint, NULL::text;
    RETURN;
  END IF;
  
  -- Get course name
  SELECT name INTO v_course_name FROM courses WHERE id = v_key.course_id;
  
  -- Key is valid
  RETURN QUERY SELECT true, ''::text, v_key.id, v_key.course_id, v_course_name;
END;
$$;

-- Function to use enrollment key
CREATE OR REPLACE FUNCTION use_enrollment_key(p_key_code text, p_user_id uuid)
RETURNS TABLE (
  success boolean,
  error_message text,
  enrollment_id bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  v_validation RECORD;
  v_existing_enrollment bigint;
  v_new_enrollment_id bigint;
BEGIN
  -- Validate the key
  SELECT * INTO v_validation FROM validate_enrollment_key(p_key_code);
  
  IF NOT v_validation.valid THEN
    RETURN QUERY SELECT false, v_validation.error_message, NULL::bigint;
    RETURN;
  END IF;
  
  -- Check if user is already enrolled
  SELECT id INTO v_existing_enrollment 
  FROM enrollments 
  WHERE user_id = p_user_id AND course_id = v_validation.course_id;
  
  IF v_existing_enrollment IS NOT NULL THEN
    RETURN QUERY SELECT false, 'You are already enrolled in this course'::text, v_existing_enrollment;
    RETURN;
  END IF;
  
  -- Create enrollment
  INSERT INTO enrollments (user_id, course_id, enrollment_key_id, enrollment_method)
  VALUES (p_user_id, v_validation.course_id, v_validation.key_id, 'key')
  RETURNING id INTO v_new_enrollment_id;
  
  -- Increment key usage count
  UPDATE enrollment_keys 
  SET current_uses = current_uses + 1,
      updated_at = now()
  WHERE id = v_validation.key_id;
  
  RETURN QUERY SELECT true, 'Successfully enrolled'::text, v_new_enrollment_id;
END;
$$;

-- Function to get enrollment key statistics
CREATE OR REPLACE FUNCTION get_enrollment_key_stats(p_key_id bigint)
RETURNS TABLE (
  total_uses bigint,
  unique_students bigint,
  active_students bigint,
  recent_enrollments jsonb
)
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
BEGIN
  RETURN QUERY
  SELECT 
    COUNT(e.id)::bigint as total_uses,
    COUNT(DISTINCT e.user_id)::bigint as unique_students,
    COUNT(DISTINCT e.user_id) FILTER (WHERE EXISTS (
      SELECT 1 FROM progress p 
      WHERE p.user_id = e.user_id 
      AND p.created_at > now() - interval '30 days'
    ))::bigint as active_students,
    jsonb_agg(
      jsonb_build_object(
        'user_id', e.user_id,
        'name', pr.name,
        'email', pr.email,
        'enrolled_at', e.enrolled_at
      ) ORDER BY e.enrolled_at DESC
    ) FILTER (WHERE e.id IS NOT NULL) as recent_enrollments
  FROM enrollments e
  LEFT JOIN profiles pr ON pr.id = e.user_id
  WHERE e.enrollment_key_id = p_key_id;
END;
$$;
