/* 
# Add Demo Course Support
1. New Column in `courses` table
   - `is_demo` (boolean) - defaults to false
*/

DO $$ 
BEGIN 
    IF NOT EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'courses' AND column_name = 'is_demo') THEN
        ALTER TABLE courses ADD COLUMN is_demo boolean DEFAULT false;
    END IF;
END $$;

-- Create demo_leads table
CREATE TABLE IF NOT EXISTS public.demo_leads (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    course_id bigint REFERENCES public.courses(id) ON DELETE CASCADE,
    full_name text NOT NULL,
    grade text NOT NULL,
    email text NOT NULL,
    phone text NOT NULL,
    level_completed text NOT NULL,
    score_details jsonb DEFAULT '{}'::jsonb,
    created_at timestamptz DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.demo_leads ENABLE ROW LEVEL SECURITY;

-- Allow public insertion for demo flow
CREATE POLICY "Public can insert demo leads" ON public.demo_leads
FOR INSERT WITH CHECK (true);

-- Allow admins to view leads
CREATE POLICY "Admins can view demo leads" ON public.demo_leads
FOR SELECT USING (
    EXISTS (
        SELECT 1 FROM profiles 
        WHERE id = auth.uid() AND role = 'admin'
    )
);
