-- ==========================================================
-- GROUP CO-TUTORS: per-group co-management (owner unaffected)
-- ==========================================================
-- A tutor who owns a student_group (student_groups.created_by) can grant
-- another tutor identical management permissions for THAT group only.
-- Enforcement is primarily in Express (src/server/routes/tutor.js,
-- src/server/routes/admin-groups.js) via the service-role client, matching
-- this codebase's established pattern (see 1768400000000-tutor_enhancements.sql
-- and 1787310253951-group_content_access_enforcement.sql) - RLS below is
-- defense-in-depth only.

CREATE TABLE IF NOT EXISTS group_tutors (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint REFERENCES student_groups(id) ON DELETE CASCADE NOT NULL,
  tutor_id uuid REFERENCES profiles(id) ON DELETE CASCADE NOT NULL,
  added_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  created_at timestamptz DEFAULT now(),
  UNIQUE(group_id, tutor_id)
);

CREATE INDEX IF NOT EXISTS idx_group_tutors_group ON group_tutors(group_id);
CREATE INDEX IF NOT EXISTS idx_group_tutors_tutor ON group_tutors(tutor_id);

ALTER TABLE group_tutors ENABLE ROW LEVEL SECURITY;

-- Owner (or admin) of the parent group can fully manage its co-tutor rows.
CREATE POLICY "Group owner or admin manages co-tutors"
ON group_tutors FOR ALL TO authenticated
USING (
  EXISTS (
    SELECT 1 FROM student_groups sg
    WHERE sg.id = group_tutors.group_id
      AND (sg.created_by = auth.uid() OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'))
  )
)
WITH CHECK (
  EXISTS (
    SELECT 1 FROM student_groups sg
    WHERE sg.id = group_tutors.group_id
      AND (sg.created_by = auth.uid() OR EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'))
  )
);

-- A co-tutor can see their own membership row (defense-in-depth; the app's
-- own routes use the service-role client and bypass this).
CREATE POLICY "Co-tutor can view own membership row"
ON group_tutors FOR SELECT TO authenticated
USING (tutor_id = auth.uid());
