/*
# Centralized "Issues & Support Center" (Admin-only)
1. New Table: support_issues - single destination for every report/support/
   contact submission in the app (question reports, student/tutor/parent
   support tickets, chatbot issues, public Contact Us).
2. RLS policies (public insert, admin-only read/write)
3. Best-effort backfill from the existing contact_messages table
*/

CREATE TABLE IF NOT EXISTS support_issues (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  -- Top-level category driving the Admin page's tabs, and who submitted it
  issue_type text NOT NULL CHECK (issue_type IN (
    'question_report', 'student_support', 'tutor_support',
    'parent_support', 'chatbot_issue', 'contact_us'
  )),
  user_type text CHECK (user_type IN ('student', 'tutor', 'parent', 'guest', 'admin')),
  submitted_by uuid REFERENCES profiles(id) ON DELETE SET NULL,

  -- Denormalized contact info - always present even for a logged-out guest
  name text NOT NULL,
  email text NOT NULL,
  phone text,

  subject text,
  category text,
  description text,

  -- Real, queryable references (not buried in metadata) for the Admin
  -- table's "Related Course/Test/Question" column
  related_course_id bigint REFERENCES courses(id) ON DELETE SET NULL,
  related_question_id bigint REFERENCES questions(id) ON DELETE SET NULL,
  related_submission_id bigint REFERENCES test_submissions(id) ON DELETE SET NULL,

  -- Flexible extra context per issue_type (e.g. question_number/topic/
  -- difficulty snapshot, or the flagged chatbot message text) so a future
  -- issue type never needs a schema change
  metadata jsonb,

  status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'in_review', 'resolved', 'archived')),
  admin_notes text,
  reviewed_by uuid REFERENCES profiles(id),
  reviewed_at timestamptz,

  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_support_issues_type ON support_issues(issue_type);
CREATE INDEX IF NOT EXISTS idx_support_issues_status ON support_issues(status);
CREATE INDEX IF NOT EXISTS idx_support_issues_submitted_by ON support_issues(submitted_by);
CREATE INDEX IF NOT EXISTS idx_support_issues_created_at ON support_issues(created_at DESC);

ALTER TABLE support_issues ENABLE ROW LEVEL SECURITY;

-- Anyone (including a logged-out Contact Us visitor) can submit
CREATE POLICY "Anyone can submit an issue"
ON support_issues FOR INSERT
WITH CHECK (true);

-- Admin-only visibility and management - this entire center is admin-only
CREATE POLICY "Admins can manage all support issues"
ON support_issues FOR SELECT TO authenticated
USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Admins can update support issues"
ON support_issues FOR UPDATE TO authenticated
USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

CREATE POLICY "Admins can delete support issues"
ON support_issues FOR DELETE TO authenticated
USING (EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'));

-- Best-effort backfill of existing public Contact Us submissions so none of
-- that history is lost from the new unified view. Guarded so re-running
-- this file never double-inserts.
INSERT INTO support_issues (issue_type, user_type, name, email, phone, description, status, created_at)
SELECT 'contact_us', 'guest', cm.full_name, cm.email, cm.mobile, cm.message, 'pending', cm.created_at
FROM contact_messages cm
WHERE NOT EXISTS (
  SELECT 1 FROM support_issues si
  WHERE si.email = cm.email AND si.created_at = cm.created_at AND si.issue_type = 'contact_us'
);
