-- Recordings / Tutorial Video Library.
--
-- A recording always links back to the SAME course/topic taxonomy the rest of the app already
-- uses (courses.id for the tutor_type-level or Full-Length Test course row, plus the canonical
-- unit/topic NAME from src/utils/taxonomy.js where a finer-grained topic is selected) - there is
-- deliberately no separate recording-only copy of SAT/ACT/AP/Full-Length Test structure, and no
-- topic_id column, because this schema has never had a canonical topics table (questions.topic is
-- free text everywhere else in the app too - see custom_prep_plans for the same finding).
CREATE TABLE IF NOT EXISTS recordings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  title text NOT NULL,
  description text,
  video_url text NOT NULL,

  -- Top-level category the Admin picked, driving which of the fields below are meaningful.
  category text NOT NULL CHECK (category IN ('sat', 'act', 'ap', 'full_length_test')),
  -- SAT only: 'reading_writing' | 'math' | null ("All SAT").
  section text,
  -- The real courses row this recording belongs to - the tutor_type-level course (e.g. "SAT Math",
  -- "ACT English", "AP Biology") for a subject recording, or the specific Full-Length Test course
  -- (e.g. "SAT Full Length Test 11") for a full_length_test recording. Null for a general
  -- "All SAT"/category-wide recording with no single course to point at.
  course_id bigint REFERENCES courses(id) ON DELETE SET NULL,
  -- Canonical unit/topic label as it appears in src/utils/taxonomy.js (e.g. "Unit 1: Chemistry of
  -- Life" / "Central Ideas and Details") - selected from that structure, never freely typed.
  unit_name text,
  topic_name text,

  recording_date date,
  recording_time time,

  status text NOT NULL DEFAULT 'draft' CHECK (status IN ('draft', 'published', 'unpublished')),

  visible_to_students boolean NOT NULL DEFAULT true,
  visible_to_tutors boolean NOT NULL DEFAULT true,

  created_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  published_at timestamptz
);

CREATE INDEX IF NOT EXISTS idx_recordings_status ON recordings(status);
CREATE INDEX IF NOT EXISTS idx_recordings_category ON recordings(category);
CREATE INDEX IF NOT EXISTS idx_recordings_course_id ON recordings(course_id);

ALTER TABLE recordings ENABLE ROW LEVEL SECURITY;

-- All access goes through the Express API (service-role key), same pattern as support_issues and
-- custom_prep_plans - no direct client-side Supabase reads/writes against this table, so a single
-- restrictive default policy (service role bypasses RLS entirely) is sufficient.
DROP POLICY IF EXISTS "Service role manages recordings" ON recordings;
CREATE POLICY "Service role manages recordings" ON recordings
  FOR ALL USING (false) WITH CHECK (false);
