-- Weekly Report cohort scheduling.
--
-- Replaces the old single-Tuesday bulk send with a fixed-weekday cohort system: each student is
-- assigned ONE weekday, permanently, and only ever receives their weekly report on that weekday -
-- never redistributed just because the student list changed. This is what lets a daily scheduler
-- stay under the email provider's daily send limit (see WEEKLY_REPORT_DAILY_LIMIT in
-- src/server/utils/weeklyReportCohorts.js) while still covering every student across the week.

-- One row per student - their permanent weekly-report weekday. `active` lets a student be taken
-- out of rotation (e.g. account suspended) without losing their assigned day if reactivated.
CREATE TABLE IF NOT EXISTS student_weekly_report_schedule (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id uuid NOT NULL UNIQUE REFERENCES profiles(id) ON DELETE CASCADE,
  weekly_report_day text NOT NULL CHECK (weekly_report_day IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY')),
  active boolean NOT NULL DEFAULT true,
  assigned_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_swrs_day_active ON student_weekly_report_schedule(weekly_report_day) WHERE active;

-- One row per (student, report_week) - the actual delivery ledger. report_week is an ISO week key
-- ("2026-W40") so every reporting cycle is unambiguous regardless of which weekday within it a
-- student is assigned to. The UNIQUE constraint is the real idempotency guarantee: a student can
-- never end up with two SENT rows for the same week even if the scheduler is triggered twice.
CREATE TABLE IF NOT EXISTS weekly_report_deliveries (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  report_week text NOT NULL,
  scheduled_day text NOT NULL CHECK (scheduled_day IN ('MONDAY', 'TUESDAY', 'WEDNESDAY', 'THURSDAY', 'FRIDAY')),
  status text NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'PROCESSING', 'SENT', 'FAILED', 'SKIPPED')),
  sent_at timestamptz,
  attempt_count integer NOT NULL DEFAULT 0,
  last_error text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (student_id, report_week)
);

CREATE INDEX IF NOT EXISTS idx_wrd_week_status ON weekly_report_deliveries(report_week, status);
CREATE INDEX IF NOT EXISTS idx_wrd_week_day_status ON weekly_report_deliveries(report_week, scheduled_day, status);

ALTER TABLE student_weekly_report_schedule ENABLE ROW LEVEL SECURITY;
ALTER TABLE weekly_report_deliveries ENABLE ROW LEVEL SECURITY;

-- Same pattern as support_issues/custom_prep_plans/recordings: all access goes through the
-- Express API via the service-role client, which bypasses RLS - these are a defense-in-depth
-- backstop, not the primary access boundary.
DROP POLICY IF EXISTS "Service role manages weekly report schedule" ON student_weekly_report_schedule;
CREATE POLICY "Service role manages weekly report schedule" ON student_weekly_report_schedule
  FOR ALL USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS "Service role manages weekly report deliveries" ON weekly_report_deliveries;
CREATE POLICY "Service role manages weekly report deliveries" ON weekly_report_deliveries
  FOR ALL USING (false) WITH CHECK (false);
