/*
# Custom Prep / Prepare More

Purely additive - one new table, no changes to any existing table/column/policy. A student
generates at most one active plan per completed Full-Length Test submission (source_submission_id
is unique), so re-generating from the same test's report updates that same plan instead of
piling up duplicates.

- analysis: frozen snapshot of the Full-Length Test breakdown used to build the plan (scores,
  per-topic accuracy, strengths/weaknesses) - kept even if the underlying submission/questions
  data changes later, so a saved plan's rationale never silently drifts.
- plan: the generated day-by-day schedule (array of days, each with subject blocks and tasks).
  Each task carries its own `completed` flag - progress is tracked inline here rather than in a
  separate table, since a plan is always read/written as one unit by its owning student.
- current_day_index: 0-based pointer into `plan.days` for "continue where I left off".
*/

CREATE TABLE IF NOT EXISTS custom_prep_plans (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  source_submission_id bigint NOT NULL REFERENCES test_submissions(id) ON DELETE CASCADE,
  course_id bigint REFERENCES courses(id) ON DELETE SET NULL,
  test_name text,

  current_score integer,
  recommended_target_min integer,
  recommended_target_max integer,
  target_score integer NOT NULL,
  hours_per_day numeric NOT NULL,
  num_days integer NOT NULL,
  total_hours numeric NOT NULL,
  difficulty_label text,

  analysis jsonb NOT NULL DEFAULT '{}'::jsonb,
  plan jsonb NOT NULL DEFAULT '{}'::jsonb,
  current_day_index integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'completed', 'archived')),

  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now(),

  UNIQUE (student_id, source_submission_id)
);

CREATE INDEX IF NOT EXISTS idx_custom_prep_plans_student_id ON custom_prep_plans(student_id);
CREATE INDEX IF NOT EXISTS idx_custom_prep_plans_submission_id ON custom_prep_plans(source_submission_id);

ALTER TABLE custom_prep_plans ENABLE ROW LEVEL SECURITY;

-- A student manages only their own plans. Admin/tutor visibility isn't needed yet (this feature
-- is student-facing only for now) - server routes use the service-role client throughout anyway,
-- matching how the rest of this app's Express routes talk to Supabase, so these policies are a
-- defense-in-depth backstop rather than the primary access boundary.
CREATE POLICY "Students manage their own custom prep plans"
ON custom_prep_plans FOR ALL TO authenticated
USING (student_id = auth.uid())
WITH CHECK (student_id = auth.uid());
