-- Global Course & Recording category visibility - a SEPARATE, data-driven layer below the
-- existing per-plan Free/Premium feature toggles (plan_settings.feature_recordings etc, left
-- completely untouched). Those control whether a FEATURE is available to a plan at all;
-- this controls which CATEGORIES are visible within that feature, platform-wide, regardless of
-- plan. e.g. plan_settings.feature_recordings=true means "this plan can use Recordings at all",
-- while a 'recordings'/'ACT' row here set to false means "nobody sees ACT recordings, on any
-- plan" - the two checks are independent and both must pass.
--
-- One row per (context, category): context is 'my_courses' or 'recordings' (room for more
-- contexts later without a schema change), category is the exact key each UI already uses
-- (student/common/StudentCourseList.jsx's activeCategory values for 'my_courses'; recordings.js's
-- category/recording_type values for 'recordings' - 'platform' there means Prep365 Tutorials).
CREATE TABLE IF NOT EXISTS category_visibility_settings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  context text NOT NULL CHECK (context IN ('my_courses', 'recordings')),
  category text NOT NULL,
  enabled boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (context, category)
);

-- Seed every known category as ON (the current, pre-this-feature behavior) so the UI never shows
-- a blank/undefined state for a category nobody has touched yet.
INSERT INTO category_visibility_settings (context, category, enabled) VALUES
  ('my_courses', 'FULL LENGTH TESTS', true),
  ('my_courses', 'SAT', true),
  ('my_courses', 'ACT', true),
  ('my_courses', 'AP', true),
  ('recordings', 'full_length_test', true),
  ('recordings', 'sat', true),
  ('recordings', 'act', true),
  ('recordings', 'ap', true),
  ('recordings', 'platform', true)
ON CONFLICT (context, category) DO NOTHING;

ALTER TABLE category_visibility_settings ENABLE ROW LEVEL SECURITY;

-- Same pattern as every other admin-managed settings table this app has (support_issues,
-- recordings, etc) - all real access goes through the Express API via the service-role client,
-- which bypasses RLS; this is a defense-in-depth backstop, not the primary access boundary.
DROP POLICY IF EXISTS "Service role manages category visibility" ON category_visibility_settings;
CREATE POLICY "Service role manages category visibility" ON category_visibility_settings
  FOR ALL USING (false) WITH CHECK (false);
