-- Recordings v3: proper group<->recording assignment relationship table.
--
-- The previous migration (1790920000000) added `assigned_recording_ids bigint[]` directly on
-- student_groups, mirroring the existing assigned_course_ids pattern. The user has since asked
-- for a real relationship table instead (group_recording_assignments), explicitly so the SAME
-- recording can be assigned to multiple groups independently, each assignment carrying its own
-- assigned_at/assigned_by/start_date/deadline/status - none of which a flat id array can hold.
-- That array column is left in place (harmless, unused) rather than dropped - nothing has ever
-- been written to it since its own migration was never applied, so there's no data to migrate
-- and no risk in leaving an inert column behind instead of an ALTER...DROP COLUMN.
CREATE TABLE IF NOT EXISTS group_recording_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  group_id bigint NOT NULL REFERENCES student_groups(id) ON DELETE CASCADE,
  recording_id bigint NOT NULL REFERENCES recordings(id) ON DELETE CASCADE,

  assigned_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  -- Denormalized alongside assigned_by - who assigned it (admin vs tutor) matters for the
  -- authorization story even if the profiles row is later deleted/role-changed.
  assigned_by_role text,
  assigned_at timestamptz NOT NULL DEFAULT now(),

  -- Optional per-ASSIGNMENT window (deliberately separate from a group's course-content
  -- start_date/end_date) - the same recording can be assigned to Group A with one deadline and
  -- Group B with a different one, which a shared group-level date column can't express.
  start_date timestamptz,
  deadline timestamptz,

  status text NOT NULL DEFAULT 'active' CHECK (status IN ('active', 'removed')),

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  UNIQUE (group_id, recording_id)
);

CREATE INDEX IF NOT EXISTS idx_group_recording_assignments_group ON group_recording_assignments(group_id);
CREATE INDEX IF NOT EXISTS idx_group_recording_assignments_recording ON group_recording_assignments(recording_id);
