-- ==========================================================
-- Notification System Tables
-- ==========================================================
-- This migration ensures all required tables for the notification
-- and reporting system exist with proper indexes and RLS policies.
-- ==========================================================

-- 1. Notification Outbox Table
-- Stores pending notifications to be processed asynchronously

CREATE TABLE IF NOT EXISTS notification_outbox (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Event Information
  event_type text NOT NULL, -- 'TEST_COMPLETED', 'WEEKLY_REPORT', 'DUE_DATE_REMINDER'
  recipient_profile_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  recipient_type text NOT NULL, -- 'student', 'parent', 'tutor', 'admin'
  
  -- Delivery Channels
  channels text[] DEFAULT ARRAY['email', 'sms', 'whatsapp'],
  
  -- Payload contains all data needed to build the notification
  payload jsonb DEFAULT '{}',
  
  -- Scheduling
  scheduled_for timestamptz DEFAULT now(),
  status text DEFAULT 'pending', -- 'pending', 'processing', 'sent', 'failed'
  
  -- Retry Logic
  attempts integer DEFAULT 0,
  max_attempts integer DEFAULT 3,
  last_error text,
  
  -- Timestamps
  sent_at timestamptz,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Indexes for notification_outbox
CREATE INDEX IF NOT EXISTS idx_notification_outbox_status 
  ON notification_outbox(status, scheduled_for) 
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_notification_outbox_recipient 
  ON notification_outbox(recipient_profile_id, status);

CREATE INDEX IF NOT EXISTS idx_notification_outbox_event_type 
  ON notification_outbox(event_type, status);

CREATE INDEX IF NOT EXISTS idx_notification_outbox_scheduled 
  ON notification_outbox(scheduled_for) 
  WHERE status IN ('pending', 'processing');

-- RLS for notification_outbox
ALTER TABLE notification_outbox ENABLE ROW LEVEL SECURITY;

-- Users can view their own notifications
CREATE POLICY "Users can view own notifications"
  ON notification_outbox FOR SELECT TO authenticated
  USING (recipient_profile_id = auth.uid());

-- System can insert notifications (bypass RLS in code)
-- Admins can view all for debugging
CREATE POLICY "Admins can view all notifications"
  ON notification_outbox FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'
  ));

-- 2. Notification Preferences Table
-- Allows users to customize which notifications they receive

CREATE TABLE IF NOT EXISTS notification_preferences (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  profile_id uuid UNIQUE NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  
  -- Event Type Preferences
  test_completed_enabled boolean DEFAULT true,
  weekly_report_enabled boolean DEFAULT true,
  due_date_enabled boolean DEFAULT true,
  achievement_enabled boolean DEFAULT true,
  
  -- Channel Preferences
  email_enabled boolean DEFAULT true,
  sms_enabled boolean DEFAULT false,
  whatsapp_enabled boolean DEFAULT false,
  
  -- Contact Overrides (if different from profile)
  phone_e164 text,
  whatsapp_e164 text,
  
  -- Timing Preferences
  quiet_hours_start time, -- e.g., '22:00' for 10 PM
  quiet_hours_end time,   -- e.g., '08:00' for 8 AM
  
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Index for quick preference lookups
CREATE INDEX IF NOT EXISTS idx_notification_preferences_profile 
  ON notification_preferences(profile_id);

-- RLS for notification_preferences
ALTER TABLE notification_preferences ENABLE ROW LEVEL SECURITY;

-- Users can view/update their own preferences
CREATE POLICY "Users can manage own preferences"
  ON notification_preferences FOR ALL TO authenticated
  USING (profile_id = auth.uid())
  WITH CHECK (profile_id = auth.uid());

-- Admins can view all preferences
CREATE POLICY "Admins can view all preferences"
  ON notification_preferences FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'
  ));

-- 3. Test Assignments Table (for due date tracking)
-- Tracks assigned tests with due dates

CREATE TABLE IF NOT EXISTS test_assignments (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  
  -- Assignment Details
  user_id uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  course_id bigint NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
  level text NOT NULL,
  
  -- Due Date
  due_at timestamptz NOT NULL,
  assigned_at timestamptz DEFAULT now(),
  assigned_by uuid REFERENCES profiles(id),
  
  -- Status Tracking
  status text DEFAULT 'assigned', -- 'assigned', 'completed', 'overdue', 'cancelled'
  completed_at timestamptz,
  
  -- Metadata
  notes text,
  priority text DEFAULT 'normal', -- 'low', 'normal', 'high', 'urgent'
  
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- Indexes for test_assignments
CREATE INDEX IF NOT EXISTS idx_test_assignments_user 
  ON test_assignments(user_id, status);

CREATE INDEX IF NOT EXISTS idx_test_assignments_due 
  ON test_assignments(due_at) 
  WHERE status = 'assigned';

CREATE INDEX IF NOT EXISTS idx_test_assignments_course 
  ON test_assignments(course_id, status);

-- RLS for test_assignments
ALTER TABLE test_assignments ENABLE ROW LEVEL SECURITY;

-- Students can view their own assignments
CREATE POLICY "Students can view own assignments"
  ON test_assignments FOR SELECT TO authenticated
  USING (user_id = auth.uid());

-- Tutors/Admins can view assignments for their students
CREATE POLICY "Tutors can view student assignments"
  ON test_assignments FOR SELECT TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM profiles p
      WHERE p.id = auth.uid()
      AND (p.role = 'tutor' OR p.role = 'admin')
    )
  );

-- Students can update their own (to mark complete)
CREATE POLICY "Students can update own assignments"
  ON test_assignments FOR UPDATE TO authenticated
  USING (user_id = auth.uid())
  WITH CHECK (user_id = auth.uid());

-- Admins/Tutors can manage all assignments
CREATE POLICY "Admins can manage all assignments"
  ON test_assignments FOR ALL TO authenticated
  USING (EXISTS (
    SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'
  ))
  WITH CHECK (EXISTS (
    SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin'
  ));

-- 4. Trigger to auto-update updated_at timestamps

CREATE OR REPLACE FUNCTION update_notification_timestamps()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Apply timestamp trigger to notification_outbox
DROP TRIGGER IF EXISTS update_notification_outbox_timestamp ON notification_outbox;
CREATE TRIGGER update_notification_outbox_timestamp
  BEFORE UPDATE ON notification_outbox
  FOR EACH ROW
  EXECUTE FUNCTION update_notification_timestamps();

-- Apply timestamp trigger to notification_preferences
DROP TRIGGER IF EXISTS update_notification_preferences_timestamp ON notification_preferences;
CREATE TRIGGER update_notification_preferences_timestamp
  BEFORE UPDATE ON notification_preferences
  FOR EACH ROW
  EXECUTE FUNCTION update_notification_timestamps();

-- Apply timestamp trigger to test_assignments
DROP TRIGGER IF EXISTS update_test_assignments_timestamp ON test_assignments;
CREATE TRIGGER update_test_assignments_timestamp
  BEFORE UPDATE ON test_assignments
  FOR EACH ROW
  EXECUTE FUNCTION update_notification_timestamps();

-- 5. Seed Default Preferences for Existing Users

INSERT INTO notification_preferences (profile_id)
SELECT id FROM profiles
WHERE id NOT IN (SELECT profile_id FROM notification_preferences)
ON CONFLICT (profile_id) DO NOTHING;

-- ==========================================================
-- Utility Views for Reporting
-- ==========================================================

-- View: Pending notifications due now
CREATE OR REPLACE VIEW v_notifications_pending AS
SELECT *
FROM notification_outbox
WHERE status = 'pending'
  AND scheduled_for <= now()
ORDER BY scheduled_for ASC;

-- View: Upcoming test assignments (next 7 days)
CREATE OR REPLACE VIEW v_test_assignments_upcoming AS
SELECT 
  a.*,
  c.name as course_name,
  p.name as student_name,
  EXTRACT(EPOCH FROM (a.due_at - now())) / 3600 as hours_until_due
FROM test_assignments a
JOIN courses c ON c.id = a.course_id
JOIN profiles p ON p.id = a.user_id
WHERE a.status = 'assigned'
  AND a.due_at BETWEEN now() AND (now() + interval '7 days')
ORDER BY a.due_at ASC;

-- ==========================================================
-- Completion Message
-- ==========================================================

DO $$
BEGIN
  RAISE NOTICE '✅ Notification system tables created successfully';
  RAISE NOTICE '   - notification_outbox: Queue for async notifications';
  RAISE NOTICE '   - notification_preferences: User notification settings';
  RAISE NOTICE '   - test_assignments: Track test due dates';
  RAISE NOTICE '   - RLS policies enabled for security';
  RAISE NOTICE '   - Indexes added for performance';
END $$;
