
import express from 'express';
import supabase from '../../supabase/supabase.js';

const router = express.Router();

router.get('/apply', async (req, res) => {
    try {
        console.log('🛠️ Applying Database Fixes...');

        // 1. Fix Uploads Table
        console.log('1️⃣ Fixing Uploads Table...');

        // We can't run raw SQL easily via JS client, 
        // BUT we can use the "RPC" trick if you have an exec_sql function (unlikely).
        // OR we can try to use standard table operations to "force" schema updates? No.

        // Since we are running in the backend, we can try to assume standard columns.
        // Failing that, we rely on the user running the SQL.

        // Wait! We can use the Postgres connection string if we had one.
        // But we only have the HTTP URL.

        // PLAN B: We will try to create a "RPC" function via the REST API? No, can't create functions.

        // OK, I'll return a JSON with the instructions and the SQL content,
        // so the user sees it in the browser when they visit this route.

        const fixSQL = `
-- COPY THIS AND RUN IN SUPABASE SQL EDITOR --

-- 1. FIX UPLOADS TABLE
DO $$ 
BEGIN 
    ALTER TABLE uploads ADD COLUMN IF NOT EXISTS category text DEFAULT 'source_document'; 
    ALTER TABLE uploads ADD COLUMN IF NOT EXISTS level text DEFAULT 'All'; 
    ALTER TABLE uploads ADD COLUMN IF NOT EXISTS section text DEFAULT 'general'; 
    ALTER TABLE uploads ADD COLUMN IF NOT EXISTS file_type text; 
    ALTER TABLE uploads ADD COLUMN IF NOT EXISTS file_url text; 
END $$;

-- 2. CREATE ENROLLMENT KEYS TABLE
CREATE TABLE IF NOT EXISTS enrollment_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_code text UNIQUE NOT NULL,
  course_id bigint REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
  created_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  creator_role text,
  max_uses integer DEFAULT NULL,
  current_uses integer DEFAULT 0,
  max_students integer DEFAULT NULL,
  valid_from timestamptz DEFAULT now(),
  valid_until timestamptz DEFAULT NULL,
  is_active boolean DEFAULT true,
  description text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 3. UPDATE ENROLLMENTS
DO $$ 
BEGIN 
    ALTER TABLE enrollments ADD COLUMN IF NOT EXISTS enrollment_key_id bigint REFERENCES enrollment_keys(id) ON DELETE SET NULL;
    ALTER TABLE enrollments ADD COLUMN IF NOT EXISTS enrollment_method text DEFAULT 'manual';
    
    ALTER TABLE questions ADD COLUMN IF NOT EXISTS upload_id bigint REFERENCES uploads(id) ON DELETE CASCADE;
    ALTER TABLE questions ADD COLUMN IF NOT EXISTS image text;
    
    -- 4. ADD LINKED STUDENTS FOR PARENT ROLES
    ALTER TABLE profiles ADD COLUMN IF NOT EXISTS linked_students UUID[] DEFAULT '{}';
    
    -- 5. ADD SCALED SCORE COLUMNS FOR ADAPTIVE TESTS
    ALTER TABLE test_submissions ADD COLUMN IF NOT EXISTS math_scaled_score integer;
    ALTER TABLE test_submissions ADD COLUMN IF NOT EXISTS reading_scaled_score integer;
END $$;
`;

        // 2. Schema Diagnostic (Best effort via select)
        let schemaInfo = "Not checked";
        try {
            const { error: diagError } = await supabase
                .from('test_submissions')
                .select('math_scaled_score, reading_scaled_score')
                .limit(1);
            
            if (diagError) {
                schemaInfo = `❌ SCHEMA MISSING: ${diagError.message}`;
            } else {
                schemaInfo = "✅ SCHEMA OK: Adaptive columns found.";
            }
        } catch (e) {
            schemaInfo = `💥 Diagnostic error: ${e.message}`;
        }

        res.send(`
            <html>
                <body style="font-family: sans-serif; padding: 40px; background: #0f172a; color: white; line-height: 1.6;">
                    <div style="max-width: 800px; margin: 0 auto;">
                        <h1 style="color: #f43f5e; font-size: 32px; font-weight: 900; margin-bottom: 8px;">🛠️ DATABASE SYSTEM DIAGNOSTIC</h1>
                        <p style="color: #94a3b8; margin-bottom: 32px;">Production Schema Verification</p>

                        <div style="background: #1e293b; padding: 24px; border-radius: 16px; border: 1px solid #334155; margin-bottom: 32px;">
                            <h3 style="margin-top: 0; color: #38bdf8;">Status: ${schemaInfo}</h3>
                            <p style="font-size: 14px; color: #94a3b8;">If you see "column does not exist", you must run the SQL below in Supabase.</p>
                        </div>

                        <h2 style="font-size: 18px; font-weight: 800; margin-bottom: 12px; display: flex; align-items: center; gap: 8px;">
                            <span style="background: #f43f5e; width: 24px; height: 24px; display: flex; align-items: center; justify-content: center; rounded-full; font-size: 12px;">!</span>
                            REQUIRED SQL FIX
                        </h2>
                        <textarea readonly style="width: 100%; height: 350px; padding: 20px; border-radius: 12px; background: #020617; border: 1px solid #334155; color: #38bdf8; font-family: monospace; font-size: 13px; margin-bottom: 20px;">${fixSQL}</textarea>
                        
                        <div style="display: flex; gap: 16px; align-items: center;">
                            <button onclick="navigator.clipboard.writeText(document.querySelector('textarea').value); this.innerText='✅ COPIED!';" style="padding: 12px 24px; background: #2563eb; color: white; border: none; border-radius: 12px; cursor: pointer; font-weight: 800; transition: all 0.2s;">
                                COPY SQL TO CLIPBOARD
                            </button>
                            <a href="https://supabase.com/dashboard/project/_/sql" target="_blank" style="color: #38bdf8; font-weight: 600; text-decoration: none; border-bottom: 1px solid #38bdf8;">Open Supabase SQL Editor →</a>
                        </div>

                        <div style="margin-top: 48px; padding-top: 24px; border-top: 1px solid #334155; font-size: 13px; color: #64748b;">
                            <p>Once you run the SQL, try submitting the adaptive test again. The 500 error should resolve immediately.</p>
                        </div>
                    </div>
                </body>
            </html>
        `);

    } catch (error) {
        console.error('Fix failed:', error);
        res.status(500).send('Error: ' + error.message);
    }
});

export default router;
