
import express from 'express';
import supabase from '../../supabase/supabase.js';

const router = express.Router();

router.get('/apply', async (req, res) => {
    try {
        console.log('🛠️ Applying Database Fixes...');

        // 1. Fix Uploads Table
        console.log('1️⃣ Fixing Uploads Table...');

        // We can't run raw SQL easily via JS client, 
        // BUT we can use the "RPC" trick if you have an exec_sql function (unlikely).
        // OR we can try to use standard table operations to "force" schema updates? No.

        // Since we are running in the backend, we can try to assume standard columns.
        // Failing that, we rely on the user running the SQL.

        // Wait! We can use the Postgres connection string if we had one.
        // But we only have the HTTP URL.

        // PLAN B: We will try to create a "RPC" function via the REST API? No, can't create functions.

        // OK, I'll return a JSON with the instructions and the SQL content,
        // so the user sees it in the browser when they visit this route.

        const fixSQL = `
-- COPY THIS AND RUN IN SUPABASE SQL EDITOR --

-- 1. FIX UPLOADS TABLE
DO $$ 
BEGIN 
    ALTER TABLE uploads ADD COLUMN IF NOT EXISTS category text DEFAULT 'source_document'; 
    ALTER TABLE uploads ADD COLUMN IF NOT EXISTS level text DEFAULT 'All'; 
    ALTER TABLE uploads ADD COLUMN IF NOT EXISTS file_type text; 
    ALTER TABLE uploads ADD COLUMN IF NOT EXISTS file_url text; 
END $$;

-- 2. CREATE ENROLLMENT KEYS TABLE
CREATE TABLE IF NOT EXISTS enrollment_keys (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  key_code text UNIQUE NOT NULL,
  course_id bigint REFERENCES courses(id) ON DELETE CASCADE NOT NULL,
  created_by uuid REFERENCES profiles(id) ON DELETE SET NULL,
  creator_role text,
  max_uses integer DEFAULT NULL,
  current_uses integer DEFAULT 0,
  max_students integer DEFAULT NULL,
  valid_from timestamptz DEFAULT now(),
  valid_until timestamptz DEFAULT NULL,
  is_active boolean DEFAULT true,
  description text,
  created_at timestamptz DEFAULT now(),
  updated_at timestamptz DEFAULT now()
);

-- 3. UPDATE ENROLLMENTS
DO $$ 
BEGIN 
    ALTER TABLE enrollments ADD COLUMN IF NOT EXISTS enrollment_key_id bigint REFERENCES enrollment_keys(id) ON DELETE SET NULL;
    ALTER TABLE enrollments ADD COLUMN IF NOT EXISTS enrollment_method text DEFAULT 'manual';
    
    ALTER TABLE questions ADD COLUMN IF NOT EXISTS upload_id bigint REFERENCES uploads(id) ON DELETE CASCADE;
    ALTER TABLE questions ADD COLUMN IF NOT EXISTS image text;
END $$;
`;

        res.send(`
            <html>
                <body style="font-family: monospace; padding: 20px; background: #f0f0f0;">
                    <h1 style="color: #e11d48;">⚠️ DATABASE UPDATE REQUIRED</h1>
                    <p>The system cannot auto-update the database schema securely.</p>
                    <p><strong>YOU MUST RUN THE FOLLOWING SQL MANUALY:</strong></p>
                    <textarea style="width: 100%; height: 400px; padding: 10px; border-radius: 5px; border: 1px solid #ccc;">${fixSQL}</textarea>
                    <br><br>
                    <button onclick="navigator.clipboard.writeText(document.querySelector('textarea').value); alert('Copied!');" style="padding: 10px 20px; background: #2563eb; color: white; border: none; border-radius: 5px; cursor: pointer; font-size: 16px;">
                        COPY TO CLIPBOARD
                    </button>
                    <p style="margin-top: 20px;">
                        1. Go to <a href="https://supabase.com/dashboard/project/_/sql" target="_blank">Supabase SQL Editor</a><br>
                        2. Paste the code<br>
                        3. Click "RUN"
                    </p>
                </body>
            </html>
        `);

    } catch (error) {
        console.error('Fix failed:', error);
        res.status(500).send('Error: ' + error.message);
    }
});

export default router;
